name: Hello world

on:
  push:
  issues:
    types:
      - opened

jobs:
  hello-world:
    runs-on: ubuntu-22.04

    steps:
      - name: Display a greeting
        run: echo "Hi from GitHub Action, I'm running on ${{ runner.os }} and I was triggered by ${{ github.actor }} on the ${{ github.event_name }} event!"
